---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Catherine James"
pagetitle: "L01 Catherine James"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[My github link](https://github.com/stat301-3-2026-spring/l01-review-Cathyj112)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

Supervised Learning contains pre categorized data. It is task driven with the objective of creating predication and predictive models. Within the supervised learning process are classification and regression model. There is a target that you are aiming to find.

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

Supervised learning uses pre categorized data and unsupervised learning uses unlabeled data. The main objective for unsupervised is pattern/structure recognition compared to supervised learning objective of creating predictions.  

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Descriptive models explain or reveals patterns and trends within the data


:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models contain a hypothesis that you are testing out using the model. Trying to explain the how and why of relationships 

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

produces the most accurate prediction possible for new data

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A mechanistic model uses an equation to come up with an answer. It typically has an assumption and itr is knowledged driven. Examples include linear and logistic regression models 

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

This type of model is not equation based and there are no assumptions of F(x). It is typically data - driven. Examples include tree based models or K nearest neighbors 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models are parametric model and Empirically driven models are non parametric 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

Parametric models are typically easier to interpret because there is a fixed/predefined relationship to see how variables impact relationships

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are typically more flexible because the model doesn't assume a fixed f(x) to describe the data. Empirically driven models adapt to the data and capture all sorts of relationships like non linear ones that parametric fails to capture well.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Typically with parametric/mechanistic models, there is high bias low variance trade off. This means there is potential for under fitting because the model can't capture irl data with so much noise. Typically with empirical/non-parametric models, there is a low bias and high variance which could lead to over fitting. The model is too complex and does well on the training data, but performs poorly on test data.  

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression produces a numeric outcome variable. Classification creates predictions for categories
:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

Stratifying by the outcome/target variable is useful because it fixes the class imbalances by pulling the same amount of proportion for each class.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross-validation splits your data into V equal parts, called folds. The model is trained V times, each time using V−1 folds for training and the remaining fold for testing, rotating which fold is used as the test set. The performance results from the RMSE are then averaged to give a more reliable estimate of how well the model will perform on new data.


:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

We might use a bootstrap resampling procedure instead of v-fold cross validation when we have a smaller dataset with the goal of estimating uncertaintity

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is where we have different hyperparameters that we can change the values of to find the best-performing model. 

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

- RMSE:The square root of the average squared differences between predicted and actual values

- MSE: The average squared difference between predicted values and actual values

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy: The proportion of correct predictions out of the total number of cases

ROC AUC: It measures how well a model separates classes across probability thresholds 

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

I believe this is a prediction problem because there is no assumption made and you are trying to predict if the calls will actually impact a customer's likelihood of churn in the next month

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

I think this is an inferential problem because you are trying to find the likelihood that a customer will churn from a high number of service calls. This is already assuming/inferring there is an existing relationship between these 2 things, but now, we are just calculating the severity of it.

:::

